FROM python:3.10-slim

RUN mkdir auth_server

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY poetry_for_auth/pyproject.toml poetry_for_auth/poetry.lock ./

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root --no-dev

COPY ./auth_server ./auth_server
RUN pip install uvicorn

WORKDIR /auth_server

# CMD ["python", "./tests/start_tests.py"]
ENTRYPOINT ["uvicorn", "--reload", "app:app", "--host", "0.0.0.0", "--port", "8000"]
