FROM python:3.10-slim

RUN mkdir info_server

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt ./

RUN pip3 install --no-cache-dir -r ./requirements.txt;

COPY ./info_server ./info_server

WORKDIR /info_server

# CMD ["python", "./tests/start_tests.py"]
ENTRYPOINT ["uvicorn", "--reload", "app:app", "--host", "0.0.0.0", "--port", "8000"]
