version: "3.9"
services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      POSTGRES_DB: "leetcode_helper"
      POSTGRES_USER: "leetcode_helper"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5555:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d leetcode_helper -U leetcode_helper"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app
    ports:
      - "8080:8000"
