FROM python:3.10-slim

RUN mkdir info_server

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY poetry/poetry_for_info/pyproject.toml poetry/poetry_for_info/poetry.lock ./

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root --no-dev

COPY ./info_server ./info_server
RUN pip install uvicorn

WORKDIR /info_server

# CMD ["python", "./tests/start_tests.py"]
ENTRYPOINT ["uvicorn", "--reload", "app:app", "--host", "0.0.0.0", "--port", "8000"]
