FROM python:3.10-slim

RUN mkdir auth_server

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.auth.txt ./

RUN pip3 install --no-cache-dir -r ./requirements.auth.txt;

COPY ./auth_server ./auth_server

WORKDIR /auth_server

# CMD ["python", "./tests/start_tests.py"]
ENTRYPOINT ["uvicorn", "--reload", "app:app", "--host", "0.0.0.0", "--port", "8000"]
